### ISSUE TITLE
Document how to compile/deploy demo app (coolstore)

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#104]
Assuming our demo application is Coolstore:  https://github.com/konveyor-ecosystem/coolstore/tree/main

As part of our demo workflow documentation, let's document how to:

- Compile the original state, Java EE code, 'main' branch
- How to deploy to a Wildfly/EAP server to verify the compiled code is running
- Compile the Quarkus version, assuming we have a 'golden solution' migrated to Quarkus in the 'quarkus' branch
- How to deploy the Quarkus app locally and verify it's functional
- How to deploy the Quarkus app to a OpenShift/k8s cluster and verify it is functional

**Comment by savitharaghunathan** [comment]
https://github.com/konveyor-ecosystem/kai/pull/180
