### ISSUE TITLE
 Server error <mixtral>:  [CRITICAL] WORKER TIMEOUT  ....    [ERROR] Worker (pid:#) was sent SIGKILL! Perhaps out of memory?

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#109]
I saw the below while attempting a run against mixtral using PR #107 

```
[2024-03-25 21:53:27 -0400] [11801] [CRITICAL] WORKER TIMEOUT (pid:12903)
[2024-03-25 21:53:28 -0400] [11801] [ERROR] Worker (pid:12903) was sent SIGKILL! Perhaps out of memory?
[2024-03-25 21:53:28 -0400] [13179] [INFO] Booting worker with pid: 13179
```

Server console output:  https://gist.github.com/jwmatthews/32cc1dedd8ecfb2c4364e38533b43fe7

**Comment by fabianvf** [comment]
I think this is due to the worker hitting its timeout and the main process killing it. I increased the worker + request timeouts to 3600 seconds and I'm not seeing the issue anymore. Waiting for the run to finish to confirm

**Comment by fabianvf** [comment]
I did see the model start 503ing with the files that had a lot of incidents, which made the whole thing restart (ie, it had processed 14/15 incidents, 503ed the last request and then started over at 1/15). I'm adding a retry mechanism for getting individual responses to try to avoid reprocessing so many incidents.
