### ISSUE TITLE
Update so we can run against the models served from IBM

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#52]
Let's update the [server code](https://github.com/konveyor-ecosystem/kai/blob/main/kai/server.py#L327) so we can run against the various models IBM is serving.

@jmontleon has sample code here to show what is needed:
https://github.com/konveyor-ecosystem/model-comparison/blob/main/compare.py

**Comment by JonahSussman** [comment]
Preliminary work done in 03308115ef2b1cc665ba81f9b87a266495cb09b0

**Comment by jwmatthews** [comment]
Fixed in PR#71
https://github.com/konveyor-ecosystem/kai/pull/71/files#diff-527a2a248f6c885a6871c1d59a621a04c1caed0fe33e2e74afae7dbfa90ff677
