### ISSUE TITLE
Automate adding vector extension to 'kai' db 

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor-ecosystem/kai#61]
Once the db is up and running, I manually add the following statement before loading the store

`CREATE EXTENSION IF NOT EXISTS vector;` 

These are the steps I follow in my local:
1. Create db container
2. `podman exec -it postgresql_database bash`
3. `psql -U postgres`
4. ` \c kai`
5. ` CREATE EXTENSION IF NOT EXISTS vector;` 
6.  exit db and container

**Comment by fabianvf** [comment]
This should automatically occur when the tables are created on server start: https://github.com/konveyor-ecosystem/kai/blob/main/kai/data/sql/create_tables.sql#L1

**Comment by savitharaghunathan** [comment]
@fabianvf Thank you. I did not notice that. I added that to avoid an error but that was before you got some changes in

**Comment by savitharaghunathan** [comment]
@fabianvf - looks like we need to be super user to create that extension
```python incident_store_advanced.py 
Connected to the PostgreSQL server.
Error initializing PSQLIncidentStore: permission denied to create extension "vector"
HINT:  Must be superuser to create this extension.```

**Comment by fabianvf** [comment]
Hmm, fun, I'll see if I can figure out a way around that

**Comment by savitharaghunathan** [comment]
Using make target to run postgres db works. Closing this issue
