### ISSUE TITLE
Cannot install dependencies on M series Mac

### ISSUE THREAD

**Issue by JonahSussman** [konveyor-ecosystem/kai#76]
Several installed libraries are exclusive to x86_64, Linux, or both, [for example](https://github.com/openai/triton?tab=readme-ov-file#compatibility). Luckily these are dependencies of dependencies, so we could switch to a package management system like Poetry, [which supports conditionally installing dependencies based on the platform](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies). While I don't foresee people running the server on a Mac, it might be good for getting more developers on board.

Specifically, it appears that `torch==2.2.0` is not well supported for M series Macs. One solution, for now, is just to install `torch==2.0.0`, ignore `torchvision==0.17.0` and `triton==2.0.0`, and let `pip` figure out the right dependencies. However, `pip freeze` will always output every installed package making it difficult to maintain. 

Another reason to pivot to a more advanced package management system is that, unless the user wants to use embeddings, there's no reason to install all the machine learning stuff on a person's machine.

**Comment by jwmatthews** [comment]
Example on MacOS arm64 

with python 3.12.2
```
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12==12.1.3.1 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-cublas-cu12==12.1.3.1
```

with python 3.11.8
```
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12==12.1.3.1 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-cublas-cu12==12.1.3.1
```

with python 3.10.3
```
ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12==12.1.3.1 (from versions: 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-cublas-cu12==12.1.3.1
```

**Comment by savitharaghunathan** [comment]
@jwmatthews I had to remove all nvidia deps, torchvision==0.17.0 and triton==2.0.0. for it to install without any errors. I think it worked for Shaaf as well.
