### ISSUE TITLE
Need to update langchain requirements:  LangChainDeprecationWarning: Importing chat models from langchain is deprecated

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#81]
```
env/lib/python3.12/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
```

**Comment by jwmatthews** [comment]
I'm unsure if this is a simple requirement change or if we need to make other changes to upgrade to a newer langchain. 

My concern is larger around the IBM Gen AI library and if it will work with newer langchain
https://ibm.github.io/ibm-generative-ai/v2.2.0/rst_source/examples.extensions.langchain.html#examples-extensions-langchain

**Comment by JonahSussman** [comment]
This is because we used `langchain.chat_models` instead of `langchain_community.chat_models`. Got a fix in the works, no langchain version change required.
